"""
Generates cases.csv — the NetSage AI troubleshooting case dataset.

Run: python scripts/generate_cases.py
Writes: cases.csv (repo root)

Each case models a realistic Packet Tracer / Cisco lab scenario with the
evidence fields required by the problem statement:
symptom, topology note, show-command output(s), expected fault, OSI layer,
concept tag, severity.
"""

import csv
import os

CASES = [

    # ---------------- VLAN (4) ----------------
    {
        "case_id": "CASE001",
        "category": "VLAN",
        "symptom": "PC0 (VLAN 10) can ping its own gateway but cannot reach PC5 (VLAN 20) even though both VLANs exist on the switch.",
        "topology": "PC0(VLAN10) -- SW1 -- Router0(sub-int Gi0/0.10, Gi0/0.20) -- SW1 -- PC5(VLAN20)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.10 192.168.10.1 YES manual up up\nGigabitEthernet0/0.20 192.168.20.1 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0.10\nC 192.168.20.0/24 is directly connected, GigabitEthernet0/0.20",
        "show_vlan_brief": "VLAN Name Status Ports\n10 STUDENTS active Fa0/1, Fa0/2\n20 STAFF active Fa0/3",
        "extra_evidence": "show interfaces trunk shows Fa0/1-3 access mode, no trunk configured between SW1 and Router0.",
        "expected_fault": "Router-on-a-stick trunk missing: the switch port toward Router0 is in access mode, so 802.1Q tagged inter-VLAN traffic is dropped.",
        "osi_layer": "Layer 2",
        "concept_tag": "VLAN trunking",
        "severity": "HIGH",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE002",
        "category": "VLAN",
        "symptom": "New PC plugged into Fa0/5 gets no VLAN connectivity; interface shows up/up but device can't reach anything on VLAN 30.",
        "topology": "PC9 -- SW2 Fa0/5 -- Router0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.30 192.168.30.1 YES manual up up",
        "show_ip_route": "C 192.168.30.0/24 is directly connected, GigabitEthernet0/0.30",
        "show_vlan_brief": "VLAN Name Status Ports\n1 default active Fa0/5\n30 SALES active Fa0/6",
        "extra_evidence": "Fa0/5 is still assigned to VLAN 1 (default) instead of VLAN 30.",
        "expected_fault": "Access port Fa0/5 was never moved into VLAN 30, so the PC lands on the default VLAN.",
        "osi_layer": "Layer 2",
        "concept_tag": "VLAN port assignment",
        "severity": "MEDIUM",
        "affected_network": "192.168.30.0/24",
    },
    {
        "case_id": "CASE003",
        "category": "VLAN",
        "symptom": "All VLAN 40 (guest) devices on SW3 can talk to each other but nothing on the rest of the network — including the gateway.",
        "topology": "Guest PCs -- SW3 -- SW1 (trunk) -- Router0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.40 192.168.40.1 YES manual up up",
        "show_ip_route": "C 192.168.40.0/24 is directly connected, GigabitEthernet0/0.40",
        "show_vlan_brief": "VLAN Name Status Ports\n40 GUEST active Fa0/10-15",
        "extra_evidence": "show interfaces trunk on SW1 shows the trunk to SW3 has 'Vlans allowed on trunk: 1,10,20,30' — VLAN 40 is not in the allowed list.",
        "expected_fault": "VLAN 40 is pruned from the trunk between SW3 and SW1, so guest traffic never reaches the router.",
        "osi_layer": "Layer 2",
        "concept_tag": "VLAN trunk pruning",
        "severity": "HIGH",
        "affected_network": "192.168.40.0/24",
    },
    {
        "case_id": "CASE004",
        "category": "VLAN",
        "symptom": "PC on VLAN 10 intermittently loses connectivity to the gateway; SW1 console is showing repeated topology change notifications.",
        "topology": "PC1 -- SW1 -- SW4 (redundant link, no STP tuning) -- Router0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.10 192.168.10.1 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0.10",
        "show_vlan_brief": "VLAN Name Status Ports\n10 STUDENTS active Fa0/1, Fa0/2, Fa0/3",
        "extra_evidence": "show spanning-tree vlan 10 shows frequent root port changes between SW1 and SW4 (redundant link, PortFast misconfigured on a trunk port).",
        "expected_fault": "Spanning-tree instability on VLAN 10 caused by a misconfigured PortFast trunk port creating an intermittent loop/re-convergence.",
        "osi_layer": "Layer 2",
        "concept_tag": "Spanning Tree Protocol",
        "severity": "MEDIUM",
        "affected_network": "192.168.10.0/24",
    },

    # ---------------- Gateway (4) ----------------
    {
        "case_id": "CASE005",
        "category": "GATEWAY",
        "symptom": "PC0 (192.168.10.10/24) cannot ping anything outside its own subnet; local subnet devices are reachable.",
        "topology": "PC0 -- SW1 -- Router0 Gi0/0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.10.1 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "PC0 ipconfig shows default gateway 192.168.10.100, which does not match the router interface IP 192.168.10.1.",
        "expected_fault": "PC0 is configured with the wrong default gateway (192.168.10.100 instead of 192.168.10.1).",
        "osi_layer": "Layer 3",
        "concept_tag": "Default gateway misconfiguration",
        "severity": "HIGH",
        "affected_network": "192.168.10.0/24",
    },
    {
        "case_id": "CASE006",
        "category": "GATEWAY",
        "symptom": "PC gets an IP via DHCP but has no internet/off-subnet access; gateway field is blank.",
        "topology": "PC3 -- SW1 -- Router0 (DHCP pool)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.10.1 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "show run | section dhcp shows pool LAN_POOL missing the 'default-router 192.168.10.1' line.",
        "expected_fault": "DHCP pool is not advertising a default-router option, so clients receive an IP/mask but no gateway.",
        "osi_layer": "Layer 3",
        "concept_tag": "DHCP option / default gateway",
        "severity": "HIGH",
        "affected_network": "192.168.10.0/24",
    },
    {
        "case_id": "CASE007",
        "category": "GATEWAY",
        "symptom": "PC can ping its own gateway IP but ARP for the gateway shows incomplete after a router reload.",
        "topology": "PC4 -- SW1 -- Router0 Gi0/1",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/1 192.168.11.1 YES manual administratively down down",
        "show_ip_route": "C 192.168.11.0/24 is directly connected, GigabitEthernet0/1",
        "show_vlan_brief": "",
        "extra_evidence": "Interface was left shut down after the last maintenance window.",
        "expected_fault": "Gateway-facing interface Gi0/1 is administratively down, so ARP for the gateway never resolves.",
        "osi_layer": "Layer 1/2",
        "concept_tag": "Interface administratively down",
        "severity": "HIGH",
        "affected_network": "192.168.11.0/24",
    },
    {
        "case_id": "CASE008",
        "category": "GATEWAY",
        "symptom": "Two PCs on the same subnet report intermittent 'destination host unreachable' when trying to reach the gateway.",
        "topology": "PC6, PC7 -- SW2 -- Router0 Gi0/0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.12.1 YES manual up up",
        "show_ip_route": "C 192.168.12.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "show ip arp on Router0 shows 192.168.12.1 also listed against a second MAC address — a duplicate IP on a misconfigured PC.",
        "expected_fault": "A second device on the LAN has been statically assigned the gateway's IP address (192.168.12.1), causing an IP conflict.",
        "osi_layer": "Layer 3",
        "concept_tag": "Duplicate IP address",
        "severity": "HIGH",
        "affected_network": "192.168.12.0/24",
    },

    # ---------------- DHCP (4) ----------------
    {
        "case_id": "CASE009",
        "category": "DHCP",
        "symptom": "PC ipconfig shows an Automatic Private IP Address (169.254.x.x); no connectivity at all.",
        "topology": "PC8 -- SW2 -- Router0 (DHCP server)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.13.1 YES manual up up",
        "show_ip_route": "C 192.168.13.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "show ip dhcp binding returns empty; show run shows no 'ip dhcp pool' block configured on Router0.",
        "expected_fault": "No DHCP pool is configured on Router0, so the client falls back to APIPA.",
        "osi_layer": "Layer 3/7",
        "concept_tag": "DHCP service missing",
        "severity": "HIGH",
        "affected_network": "192.168.13.0/24",
    },
    {
        "case_id": "CASE010",
        "category": "DHCP",
        "symptom": "Most PCs on VLAN 20 get addresses fine, but new PCs added this week fail to get an IP during busy hours.",
        "topology": "20 PCs -- SW3 -- Router0 (DHCP pool 192.168.20.0/28)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.20 192.168.20.1 YES manual up up",
        "show_ip_route": "C 192.168.20.0/28 is directly connected, GigabitEthernet0/0.20",
        "show_vlan_brief": "VLAN Name Status Ports\n20 STAFF active Fa0/1-24",
        "extra_evidence": "show ip dhcp pool STAFF_POOL shows 'Total addresses: 14, Leased: 14' — pool exhausted (network configured as /28 for 20+ hosts).",
        "expected_fault": "DHCP pool is undersized (/28, 14 usable addresses) for the number of hosts on VLAN 20; the pool is exhausted.",
        "osi_layer": "Layer 3/7",
        "concept_tag": "DHCP pool exhaustion",
        "severity": "MEDIUM",
        "affected_network": "192.168.20.0/28",
    },
    {
        "case_id": "CASE011",
        "category": "DHCP",
        "symptom": "PCs on VLAN 30 (a different subnet from the router's DHCP pool) never receive an address.",
        "topology": "PCs(VLAN30) -- SW1 -- Router0 sub-int Gi0/0.30 -- (DHCP pool defined only for VLAN 10)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.30 192.168.30.1 YES manual up up",
        "show_ip_route": "C 192.168.30.0/24 is directly connected, GigabitEthernet0/0.30",
        "show_vlan_brief": "VLAN Name Status Ports\n30 SALES active Fa0/6-9",
        "extra_evidence": "show run | include ip helper-address returns nothing on Gi0/0.30; DHCP pool for 192.168.30.0/24 does not exist.",
        "expected_fault": "No DHCP pool exists for the 192.168.30.0/24 scope and no ip helper-address is forwarding requests to a DHCP server.",
        "osi_layer": "Layer 3/7",
        "concept_tag": "DHCP relay / scope missing",
        "severity": "HIGH",
        "affected_network": "192.168.30.0/24",
    },
    {
        "case_id": "CASE012",
        "category": "DHCP",
        "symptom": "One specific PC always gets 192.168.10.5 while a printer at the same address goes offline whenever the PC boots.",
        "topology": "PC2, Printer0 -- SW1 -- Router0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.10.1 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "Printer0 is statically set to 192.168.10.5, which falls inside the DHCP pool range 192.168.10.2-192.168.10.50 (no exclusion configured).",
        "expected_fault": "The statically-assigned printer address was never excluded from the DHCP pool (missing ip dhcp excluded-address), so DHCP hands the same address to a PC.",
        "osi_layer": "Layer 3",
        "concept_tag": "DHCP excluded-address / duplicate IP",
        "severity": "MEDIUM",
        "affected_network": "192.168.10.0/24",
    },

    # ---------------- DNS (4) ----------------
    {
        "case_id": "CASE013",
        "category": "DNS",
        "symptom": "PC can ping Server0's IP (192.168.20.10) directly but 'ping server0.netsage.local' fails with 'Ping request could not find host'.",
        "topology": "PC5 -- SW1 -- Router0 -- Server0 (DNS server)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.20.1 YES manual up up",
        "show_ip_route": "C 192.168.20.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "PC5 ipconfig /all shows DNS server 192.168.20.99, but the actual DNS service in Packet Tracer is running on Server0 at 192.168.20.10.",
        "expected_fault": "PC5 is pointed at the wrong DNS server address (192.168.20.99 instead of 192.168.20.10), so name resolution fails while raw IP connectivity works.",
        "osi_layer": "Layer 7",
        "concept_tag": "DNS misconfiguration",
        "severity": "MEDIUM",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE014",
        "category": "DNS",
        "symptom": "All PCs in the lab can reach the DNS server IP but every hostname lookup times out.",
        "topology": "Multiple PCs -- SW1 -- Router0 -- Server0 (DNS)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.20.1 YES manual up up",
        "show_ip_route": "C 192.168.20.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "Server0 DNS Services tab shows the service toggle set to Off.",
        "expected_fault": "The DNS service on Server0 is disabled, so no client on the network can resolve names even though the host is reachable.",
        "osi_layer": "Layer 7",
        "concept_tag": "DNS service down",
        "severity": "MEDIUM",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE015",
        "category": "DNS",
        "symptom": "www.netsage.local resolves for internal PCs but resolves to the wrong IP, sending users to a decommissioned test server.",
        "topology": "PC -- SW1 -- Router0 -- Server0 (DNS)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.20.1 YES manual up up",
        "show_ip_route": "C 192.168.20.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "Server0 DNS record for www.netsage.local points to 192.168.20.50 (old test server), not 192.168.20.10 (current web server).",
        "expected_fault": "A stale A record on the DNS server points www.netsage.local at the decommissioned server's IP.",
        "osi_layer": "Layer 7",
        "concept_tag": "Stale DNS record",
        "severity": "LOW",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE016",
        "category": "DNS",
        "symptom": "Only PCs on VLAN 30 cannot resolve DNS names; VLAN 10 and 20 work fine, and the DNS server is on VLAN 20.",
        "topology": "PC(VLAN30) -- SW1 -- Router0 -- Server0(VLAN20, DNS)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.30 192.168.30.1 YES manual up up",
        "show_ip_route": "C 192.168.30.0/24 is directly connected, GigabitEthernet0/0.30\n(missing) 192.168.20.0/24",
        "show_vlan_brief": "VLAN Name Status Ports\n30 SALES active Fa0/6",
        "extra_evidence": "show ip route on Router0 has no entry at all for 192.168.20.0/24 despite the sub-interface for VLAN 20 existing — route was manually removed during testing.",
        "expected_fault": "The route to the DNS server's subnet (192.168.20.0/24) is missing from the routing table, so VLAN 30 DNS queries never reach the server.",
        "osi_layer": "Layer 3",
        "concept_tag": "Missing route affecting DNS reachability",
        "severity": "HIGH",
        "affected_network": "192.168.20.0/24",
    },

    # ---------------- Routing (4) ----------------
    {
        "case_id": "CASE017",
        "category": "ROUTING",
        "symptom": "PC0 (192.168.10.10) can ping its gateway but cannot reach Server0 (192.168.20.10) on the other side of Router0.",
        "topology": "PC0 -- SW1 -- Router0 -- Server0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.10.1 YES manual up up\nGigabitEthernet0/1 192.168.20.1 YES manual administratively down down",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "Gi0/1 toward the server subnet is administratively down, so 192.168.20.0/24 never appears in the routing table.",
        "expected_fault": "Gi0/1 is shut down, which removes the directly-connected route to 192.168.20.0/24 from the routing table.",
        "osi_layer": "Layer 3",
        "concept_tag": "Interface down removes connected route",
        "severity": "HIGH",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE018",
        "category": "ROUTING",
        "symptom": "Two-router topology; PCs behind Router2 cannot reach PCs behind Router1 even though both LANs work locally.",
        "topology": "PC(LAN1) -- Router1 -- Router2 -- PC(LAN2)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nSerial0/0/0 10.0.0.1 YES manual up up\nGigabitEthernet0/0 192.168.10.1 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0\nC 10.0.0.0/30 is directly connected, Serial0/0/0",
        "show_vlan_brief": "",
        "extra_evidence": "Router1 has no static route or routing protocol configured for 192.168.20.0/24 (Router2's LAN); show run has no 'ip route' or 'router ospf' entries.",
        "expected_fault": "No static route or dynamic routing protocol is configured on Router1 for the remote LAN (192.168.20.0/24) behind Router2.",
        "osi_layer": "Layer 3",
        "concept_tag": "Missing static/dynamic route",
        "severity": "HIGH",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE019",
        "category": "ROUTING",
        "symptom": "OSPF neighbors keep flapping between Router1 and Router2; intermittent packet loss to remote LAN.",
        "topology": "Router1 <--OSPF--> Router2",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nSerial0/0/0 10.0.0.1 YES manual up up",
        "show_ip_route": "O 192.168.20.0/24 [110/782] via 10.0.0.2, Serial0/0/0 (intermittently present)",
        "show_vlan_brief": "",
        "extra_evidence": "show ip ospf neighbor shows the neighbor state cycling INIT -> 2-WAY -> DOWN; Router1 hello-interval is 10s while Router2's is set to 5s (mismatch).",
        "expected_fault": "OSPF hello/dead timer mismatch between Router1 and Router2 is preventing a stable adjacency, causing the route to flap.",
        "osi_layer": "Layer 3",
        "concept_tag": "OSPF timer mismatch",
        "severity": "MEDIUM",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE020",
        "category": "ROUTING",
        "symptom": "Traffic to the internet-facing subnet works, but traffic to a newly added branch subnet (192.168.50.0/24) times out.",
        "topology": "HQ Router -- WAN -- Branch Router (192.168.50.0/24 LAN)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nSerial0/0/1 10.1.1.1 YES manual up up",
        "show_ip_route": "C 10.1.1.0/30 is directly connected, Serial0/0/1\nS* 0.0.0.0/0 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "show run shows a default route pointing to the internet but no static route for 192.168.50.0/24 via the branch WAN link.",
        "expected_fault": "A default route exists for internet traffic, but no specific route was added for the new branch subnet 192.168.50.0/24, so traffic is sent the wrong way (or dropped).",
        "osi_layer": "Layer 3",
        "concept_tag": "Missing static route for new subnet",
        "severity": "HIGH",
        "affected_network": "192.168.50.0/24",
    },

    # ---------------- ACL (4) ----------------
    {
        "case_id": "CASE021",
        "category": "ACL",
        "symptom": "PC0 in VLAN 30 can ping Server0 in VLAN 20 (gateway works, route exists) but cannot open a web page (HTTP) hosted there.",
        "topology": "PC0(VLAN30) -- Router0 -- Server0(VLAN20)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.20 192.168.20.1 YES manual up up\nGigabitEthernet0/0.30 192.168.30.1 YES manual up up",
        "show_ip_route": "C 192.168.20.0/24 is directly connected, GigabitEthernet0/0.20\nC 192.168.30.0/24 is directly connected, GigabitEthernet0/0.30",
        "show_vlan_brief": "",
        "extra_evidence": "show access-lists shows ACL 101 applied inbound on Gi0/0.30: 'permit icmp any any', then 'deny tcp any any eq 80', 'deny ip any any' — HTTP is explicitly blocked.",
        "expected_fault": "Inbound ACL 101 on Gi0/0.30 permits ICMP but explicitly denies TCP port 80, blocking HTTP while allowing ping.",
        "osi_layer": "Layer 3/4",
        "concept_tag": "ACL blocking specific traffic",
        "severity": "MEDIUM",
        "affected_network": "192.168.20.0/24",
    },
    {
        "case_id": "CASE022",
        "category": "ACL",
        "symptom": "After adding a new 'permit' line to an ACL, guest VLAN traffic to the internet stopped completely.",
        "topology": "Guest VLAN -- Router0 (ACL on outbound WAN interface)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/1 203.0.113.1 YES manual up up",
        "show_ip_route": "S* 0.0.0.0/0 via 203.0.113.254",
        "show_vlan_brief": "",
        "extra_evidence": "show access-lists shows the new permit line was appended AFTER an existing 'deny ip any any', making it unreachable — implicit/explicit deny at the top now matches everything.",
        "expected_fault": "The new permit rule was added after an existing 'deny ip any any', so it never takes effect and all guest traffic is denied.",
        "osi_layer": "Layer 3/4",
        "concept_tag": "ACL rule ordering",
        "severity": "HIGH",
        "affected_network": "203.0.113.0/24",
    },
    {
        "case_id": "CASE023",
        "category": "ACL",
        "symptom": "Remote admin cannot SSH into Router0 from the management subnet even though the SSH service and credentials are confirmed correct.",
        "topology": "AdminPC(192.168.99.5) -- Router0 (vty ACL)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.99.1 YES manual up up",
        "show_ip_route": "C 192.168.99.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "show run | section line vty shows 'access-class 10 in' and ACL 10 only permits 192.168.99.10, not the admin's actual address 192.168.99.5.",
        "expected_fault": "The vty access-class ACL only permits a single host (192.168.99.10) and does not include the admin's actual IP (192.168.99.5).",
        "osi_layer": "Layer 3/7",
        "concept_tag": "Management-plane ACL too restrictive",
        "severity": "MEDIUM",
        "affected_network": "192.168.99.0/24",
    },
    {
        "case_id": "CASE024",
        "category": "ACL",
        "symptom": "Server0 cannot send DNS responses back to clients even though the DNS service is confirmed running and reachable inbound.",
        "topology": "Clients -- Router0 (ACL) -- Server0 (DNS)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.20.1 YES manual up up",
        "show_ip_route": "C 192.168.20.0/24 is directly connected, GigabitEthernet0/0",
        "show_vlan_brief": "",
        "extra_evidence": "ACL 102 outbound on Gi0/0 permits UDP port 53 from clients to server, but has no matching return rule for UDP source port 53 back to clients (ACL not applied as reflexive/established).",
        "expected_fault": "The ACL only permits DNS queries outbound to the server but never explicitly permits the UDP/53 responses back, blocking replies.",
        "osi_layer": "Layer 3/4",
        "concept_tag": "ACL missing return traffic",
        "severity": "MEDIUM",
        "affected_network": "192.168.20.0/24",
    },

    # ---------------- NAT (4) ----------------
    {
        "case_id": "CASE025",
        "category": "NAT",
        "symptom": "Internal PCs can ping each other and the router's inside interface, but nothing reaches the simulated internet (ISP router).",
        "topology": "PC -- SW1 -- Router0 (NAT) -- ISP",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0 192.168.10.1 YES manual up up\nGigabitEthernet0/1 203.0.113.5 YES manual up up",
        "show_ip_route": "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0\nS* 0.0.0.0/0 via 203.0.113.1",
        "show_vlan_brief": "",
        "extra_evidence": "show ip nat translations is empty; show run shows 'ip nat inside'/'ip nat outside' are missing from the interfaces entirely.",
        "expected_fault": "NAT is configured with an access-list and pool, but the 'ip nat inside' and 'ip nat outside' interface commands were never applied, so no translation occurs.",
        "osi_layer": "Layer 3",
        "concept_tag": "NAT interface roles not applied",
        "severity": "HIGH",
        "affected_network": "192.168.10.0/24",
    },
    {
        "case_id": "CASE026",
        "category": "NAT",
        "symptom": "Only one internal PC at a time can reach the internet; a second PC's traffic silently fails while the first is active.",
        "topology": "Multiple PCs -- Router0 (static NAT, not PAT) -- ISP",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/1 203.0.113.5 YES manual up up",
        "show_ip_route": "S* 0.0.0.0/0 via 203.0.113.1",
        "show_vlan_brief": "",
        "extra_evidence": "show run shows 'ip nat inside source list 1 pool INSIDE-POOL' without the 'overload' keyword, and INSIDE-POOL only has one public address — no PAT, so only one simultaneous translation is possible.",
        "expected_fault": "NAT pool is configured without 'overload' (PAT), so only one internal host can be translated to the single public address at a time.",
        "osi_layer": "Layer 3/4",
        "concept_tag": "NAT overload / PAT missing",
        "severity": "MEDIUM",
        "affected_network": "203.0.113.0/24",
    },
    {
        "case_id": "CASE027",
        "category": "NAT",
        "symptom": "External users cannot reach the internally-hosted web server via the public IP, even though NAT overload for outbound traffic works fine.",
        "topology": "Internet -- Router0 (NAT) -- Server0 (192.168.10.10, web server)",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/1 203.0.113.5 YES manual up up",
        "show_ip_route": "S* 0.0.0.0/0 via 203.0.113.1",
        "show_vlan_brief": "",
        "extra_evidence": "show run has 'ip nat inside source list 1 interface GigabitEthernet0/1 overload' for outbound PAT, but no static 'ip nat inside source static tcp 192.168.10.10 80 203.0.113.5 80' entry for inbound port forwarding.",
        "expected_fault": "Outbound PAT/overload is configured, but there is no static NAT/port-forward rule exposing Server0's port 80 to the public interface.",
        "osi_layer": "Layer 3/4",
        "concept_tag": "NAT static port forwarding missing",
        "severity": "HIGH",
        "affected_network": "203.0.113.0/24",
    },
    {
        "case_id": "CASE028",
        "category": "NAT",
        "symptom": "PCs on VLAN 30 cannot reach the internet, while PCs on VLAN 10 and 20 (also behind the same router) work fine.",
        "topology": "PC(VLAN10,20,30) -- Router0 (NAT ACL) -- ISP",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.30 192.168.30.1 YES manual up up",
        "show_ip_route": "C 192.168.30.0/24 is directly connected, GigabitEthernet0/0.30\nS* 0.0.0.0/0 via 203.0.113.1",
        "show_vlan_brief": "VLAN Name Status Ports\n30 SALES active Fa0/6",
        "extra_evidence": "show access-lists shows the NAT source ACL 1 only includes 'permit 192.168.10.0 0.0.0.255' and 'permit 192.168.20.0 0.0.0.255' — 192.168.30.0/24 was never added.",
        "expected_fault": "The NAT source access-list does not include the 192.168.30.0/24 network, so VLAN 30 traffic is never translated and dropped at the internet edge.",
        "osi_layer": "Layer 3",
        "concept_tag": "NAT source ACL incomplete",
        "severity": "MEDIUM",
        "affected_network": "192.168.30.0/24",
    },

    # ---------------- Wireless (4) ----------------
    {
        "case_id": "CASE029",
        "category": "WIRELESS",
        "symptom": "Laptop can see the 'NetSage-Staff' SSID but authentication fails every time with the correct password.",
        "topology": "Laptop -- WLAN (WPA2-PSK) -- AP0 -- SW1",
        "show_ip_interface_brief": "",
        "show_ip_route": "",
        "show_vlan_brief": "",
        "extra_evidence": "AP0 Security config shows WPA2-PSK with passphrase 'St@ffNet2025', but the laptop's saved profile has an old passphrase 'StaffNet2024' cached.",
        "expected_fault": "The laptop has a stale cached Wi-Fi passphrase that no longer matches the AP's WPA2-PSK key after a password rotation.",
        "osi_layer": "Layer 2",
        "concept_tag": "WPA2-PSK mismatch",
        "severity": "LOW",
        "affected_network": "192.168.40.0/24",
    },
    {
        "case_id": "CASE030",
        "category": "WIRELESS",
        "symptom": "Guest Wi-Fi clients associate to the AP and get an IP address, but can also reach the internal staff file server directly.",
        "topology": "Guest laptop -- AP1(VLAN40) -- SW3 -- Router0",
        "show_ip_interface_brief": "Interface IP-Address OK? Method Status Protocol\nGigabitEthernet0/0.40 192.168.40.1 YES manual up up",
        "show_ip_route": "C 192.168.40.0/24 is directly connected, GigabitEthernet0/0.40",
        "show_vlan_brief": "VLAN Name Status Ports\n40 GUEST active Fa0/10",
        "extra_evidence": "No ACL is applied on Gi0/0.40 to isolate guest traffic from the internal 192.168.10.0/24 staff subnet — guest VLAN exists but has no isolation policy.",
        "expected_fault": "Guest VLAN 40 has no inter-VLAN ACL restricting access to internal subnets, so guest devices can reach the internal staff server (security/isolation issue).",
        "osi_layer": "Layer 3",
        "concept_tag": "Guest network isolation (ACL)",
        "severity": "HIGH",
        "affected_network": "192.168.40.0/24",
    },
    {
        "case_id": "CASE031",
        "category": "WIRELESS",
        "symptom": "Wireless clients near the far end of the building repeatedly disconnect and reconnect, wired clients are unaffected.",
        "topology": "Laptop -- AP2 -- SW2 -- Router0",
        "show_ip_interface_brief": "",
        "show_ip_route": "",
        "show_vlan_brief": "",
        "extra_evidence": "AP2 and AP3 (in the adjacent room) are both configured on channel 6 with high power, causing co-channel interference at the overlap zone.",
        "expected_fault": "Overlapping access points on the same 2.4GHz channel (channel 6) are causing co-channel interference and client disconnects.",
        "osi_layer": "Layer 1",
        "concept_tag": "Wireless channel interference",
        "severity": "MEDIUM",
        "affected_network": "192.168.41.0/24",
    },
    {
        "case_id": "CASE032",
        "category": "WIRELESS",
        "symptom": "A specific laptop cannot associate with the AP at all, error says 'network security key mismatch', while all other devices connect fine.",
        "topology": "Laptop -- AP0",
        "show_ip_interface_brief": "",
        "show_ip_route": "",
        "show_vlan_brief": "",
        "extra_evidence": "AP0 is configured for WPA2-PSK, but the specific laptop's wireless adapter is manually set to WEP (leftover config from a different network).",
        "expected_fault": "The laptop's wireless adapter is configured for WEP security while the AP uses WPA2-PSK — a security-mode mismatch.",
        "osi_layer": "Layer 2",
        "concept_tag": "Wireless security mode mismatch",
        "severity": "LOW",
        "affected_network": "192.168.40.0/24",
    },
]

FIELDNAMES = [
    "case_id", "category", "symptom", "topology",
    "show_ip_interface_brief", "show_ip_route", "show_vlan_brief",
    "extra_evidence", "expected_fault", "osi_layer", "concept_tag",
    "severity", "affected_network",
]

if __name__ == "__main__":
    out_path = os.path.join(os.path.dirname(__file__), "..", "cases.csv")
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        writer.writeheader()
        for case in CASES:
            writer.writerow(case)
    print(f"Wrote {len(CASES)} cases to {os.path.abspath(out_path)}")
